name: Test Action

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4

      - name: Run a one line script
        run: echo Hello , world!
