# This is a basic workflow to help you get started with Actions

name: Testing Action

# Controls when the workflow will run
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a index
        run: node index